id: de.gematik.isip
canonical: https://gematik.de/fhir/ISiP
name: ISIP
status: draft
version: 1.0.0-ballot
fhirVersion: 4.0.1
FSHOnly: true
publisher:
  name: Gematik GmbH
dependencies:
  de.gematik.isik-basismodul: 
    uri: https://gematik.de/fhir/ISiK/ImplementationGuide/ISiK-basismodul
    version: 2.0.0-ballot3
  de.basisprofil.r4: 1.3.2
  kbv.mio.ueberleitungsbogen: 1.0.0-kommentierung
